#服务配置
server:
 port: 80
 context-path: /wxboot
 
#mysql配置
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/wxboot
  username: root
  password: sysroot
  driverClassName: com.mysql.jdbc.Driver
  max-active: 20
  max-idle: 8
  min-idle: 8
  initial-size: 10
  
#Mybatis mapper.xml配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*/*.xml